/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;


public class VistaElemento extends javax.swing.JPanel {

    /**
     * Creates new form VistaElemento
     */
    public VistaElemento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numero = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        numero.setEditable(false);
        numero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numero.setText("jTextField1");
        numero.setBorder(null);
        numero.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        numero.setEnabled(false);
        numero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numeroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                numeroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                numeroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(numero, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void numeroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeroMouseEntered
        // TODO add your handling code here:
        numero.setBackground(Color.red);
        this.setBackground(Color.red);
        
    }//GEN-LAST:event_numeroMouseEntered

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
         
    }//GEN-LAST:event_formMouseEntered

    private void numeroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeroMouseExited
        this.setBackground(Color.white);
        numero.setBackground(Color.white);
    }//GEN-LAST:event_numeroMouseExited

    private void numeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeroMouseClicked
        // TODO add your handling code here:
        numero.setBackground(Color.yellow);
    }//GEN-LAST:event_numeroMouseClicked

    public void recibeModelo(Integer i) {
        this.numero.setText(i.toString());
        repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField numero;
    // End of variables declaration//GEN-END:variables
}
